### ISSUE TITLE
ToJSON returns original vcf version number and not 4.0

### ISSUE THREAD

**Issue by digitalpixies** [jhermsmeier/node-vcf#10]
running the following on a vcf 2.1 will return version 2.1 attribute in the jcard.

var card = vCard.parse(string);
var jcard = card.toJSON();

I assume we can get a 4.0 version by doing:

var card = vCard.parse(string);
card = vCard.parse(card.toString('4.0'));
var jcard = card.toJSON();

If that's the case, then it might be more obvious for a user to call a function like toJCard() that will do that.

**Comment by jhermsmeier** [comment]
Quickly eyeballed the spec, and couldn't find anything that requires it to be 4.0 – the jCard is just the representation of the vCard in a different format; so whichever version the vCard has is reflected in its jCard representation. I'm not sure if this is how it's supposed to be – if you can point me somewhere that has more info on this particular case, then I'd be happy to adjust this.

Introducting a `.toJCard( [version='4.0'] )` is a good idea – I'll see to implementing that shortly, thanks!

**Comment by digitalpixies** [comment]
From https://tools.ietf.org/html/rfc7095

> 3.3.1.1.  The VERSION Property

   The vCard format specification [RFC6350] defines the "VERSION"
   property to be mandatory.  The jCard "version" property MUST be
   represented in the corresponding jCard component, with the same value
   as in the vCard. vCards that conform to RFC 6350 will contain the
   value "4.0".

I'm using this as my reference for writing my vcf converter:
https://en.wikipedia.org/wiki/VCard

It also lists a bunch of attributes that are supported/changed based on version number.

Keep up to great work!

**Comment by jhermsmeier** [comment]
I totally forgot about checking the RFC, and am feeling mildly ashamed now.
I'll dig through it and see to making this module RFC compliant.
Thanks again for reporting this!

**Comment by jhermsmeier** [comment]
I added `vcard.toJCard( [version='4.0'] )` in version `1.1.0` now, which should hopefully give you the expected jCard output – I'll continue to go through the RFCs and see what else I missed.
Thanks again!
