### ISSUE TITLE
Issues if dealing with vcf with multiple cards

### ISSUE THREAD

**Issue by ajmas** [jhermsmeier/node-vcf#11]
The library appears to run into issues if a vcf file contains multiple vCards. What I see is the records from all the vCards are merged into one entry.

For example (trimmed):

```
vCard {
  version: '3.0',
  data: 
   { version: 
      [ [String: '3.0'],
        [String: '3.0'],
        [String: '3.0'],
        [String: '3.0'],
        [String: '3.0'],
        [String: '3.0'],
        [String: '3.0'],
        [String: '3.0'],
        [String: '3.0'],
        [String: '3.0'],
        [String: '3.0'],
        [String: '3.0'],
        [String: '3.0'],
        [String: '3.0'] ],
     prodid: 
      [ [String: '-//Apple Inc.//Mac OS X 10.12.1//EN'],
        [String: '-//Apple Inc.//Mac OS X 10.12.1//EN'],
        [String: '-//Apple Inc.//Mac OS X 10.12.1//EN'],
        [String: '-//Apple Inc.//Mac OS X 10.12.1//EN'],
        [String: '-//Apple Inc.//Mac OS X 10.12.1//EN'],
        [String: '-//Apple Inc.//Mac OS X 10.12.1//EN'],
        [String: '-//Apple Inc.//Mac OS X 10.12.1//EN'],
        [String: '-//Apple Inc.//Mac OS X 10.12.1//EN'],
        [String: '-//Apple Inc.//Mac OS X 10.12.1//EN'],
        [String: '-//Apple Inc.//Mac OS X 10.12.1//EN'],
        [String: '-//Apple Inc.//Mac OS X 10.12.1//EN'],
        [String: '-//Apple Inc.//Mac OS X 10.12.1//EN'],
        [String: '-//Apple Inc.//Mac OS X 10.12.1//EN'],
        [String: '-//Apple Inc.//Mac OS X 10.12.1//EN'] ],
     n: 
      [ [String: 'Matters;Sylvie;;;'],
        [String: 'Dawson;Jesse;;;'],
        [String: 'Kelsdaughter;Jen;;;'],
        [String: ';;;;'],
        [String: 'Jameson;Jen;;;'],
        [String: ';;;;'],
        [String: 'Dawson;Marc;;;'],
        [String: ';Agathe;;;'],
        [String: ';;;;'],
        [String: 'Doe;John;;;'],
        [String: 'Vino;Vito;;;'],
        [String: ';Alexei;;;'],
        [String: 'Boucher;Marie-Claude;;;'],
        [String: ';;;;'] ],
...
```

It would be useful to have this scenario supported, even if it via a new function ``parseMulti() ``, as to not break assumptions of code depending on current design.

**Comment by ajmas** [comment]
Looking at the source I see ``parseMultiple()`` already exists. Testing shows this is what I should be using.

**Comment by jwerre** [comment]
This should just be the default. Why would want to combine all your contacts into one object?

**Comment by jhermsmeier** [comment]
@jwerre If you think this needs changing, then please do file a new issue, or – *even better* – send a PR.

**Comment by ajmas** [comment]
@jhermsmeier Is there any benefit of using `parse()` over `parseMultiple()`? 

BTW a simple fix would simply to update the readme with indication of `parseMultiple()`. One risk of changing the default behaviour of `parse()` is breaking existing code, that assumes a single, non-array, object is returned.

**Comment by jhermsmeier** [comment]
@ajmas to be honest, I don't recall what the reasoning behind it was. I'm more than happy to change the API to default to parsing multiple objects from an input for the static `vCard.parse()`, which will of course make it version 2.0.0 as it's a breaking change, as that seems to be what people expect and would rather like to use.

**Comment by ajmas** [comment]
@jhermsmeier okay sounds good. In the meantime do you think the PR for the documentation change for the 1.x branch is an acceptable stop-gap?

**Comment by jhermsmeier** [comment]
@ajmas yup, just reviewed :)

**Comment by jhermsmeier** [comment]
@ajmas want to have a look at #15, and tell me if I missed anything?

**Comment by zacharytyhacz** [comment]
This issue is still is still persisting for me. 

Using ```"vcf": "^2.0.4"```

I am parsing this that is straight from Google Contacts:
```
BEGIN:VCARD
VERSION:3.0
FN:Bolt Action
N:Action;Bolt;;;
item1.EMAIL;TYPE=INTERNET:boltaction@mmmm.com
item1.X-ABLabel:
END:VCARD
BEGIN:VCARD
VERSION:3.0
FN:Brenna Damatta
N:Damatta;Brenna;;;
item1.EMAIL;TYPE=INTERNET:brenna@mmmm.com
item1.X-ABLabel:
END:VCARD
```
It is returning one vcard object merging the `fn`, `adr`, `n`, etc ,etc making it extra verbose to loop through and separate out the date per contact.

Each field is an array containing data from both contacts.
![image](https://user-images.githubusercontent.com/38140593/60115243-7f8c1280-9743-11e9-9ba4-65922b06ad62.png)

**Comment by jhermsmeier** [comment]
@zacharytyhacz I suspect that's happening because you're calling `.parse()` on a vCard instance, not on the constructor. Note the difference between [parsing a single vcard](https://github.com/jhermsmeier/node-vcf#parsing-a-single-vcard) and [parsing multiple vcards](https://github.com/jhermsmeier/node-vcf#parsing-multiple-vcards) in the README

**Comment by zacharytyhacz** [comment]
@jhermsmeier , yes that is the method I used, `.parse`. I have a work around at the moment, using the same ReGex you use in the source to seperate the file at `BEGIN:VCARD` and then individually parsing each as a single vcard with the other `new vCard().parse(<source>)`

**Comment by jhermsmeier** [comment]
@zacharytyhacz can you post an example of what you're doing? I cannot reproduce that in any way, i.e. see:

```js
> var vCard = require( '.' )
undefined

> var value = `BEGIN:VCARD
... VERSION:3.0
... FN:Bolt Action
... N:Action;Bolt;;;
... item1.EMAIL;TYPE=INTERNET:boltaction@mmmm.com
... item1.X-ABLabel:
... END:VCARD
... BEGIN:VCARD
... VERSION:3.0
... FN:Brenna Damatta
... N:Damatta;Brenna;;;
... item1.EMAIL;TYPE=INTERNET:brenna@mmmm.com
... item1.X-ABLabel:
... END:VCARD`
undefined

> vCard.parse( value )
[
  vCard {
    version: '3.0',
    data: {
      version: Property {},
      fn: Property {},
      n: Property {},
      email: [Property]
    }
  },
  vCard {
    version: '3.0',
    data: {
      version: Property {},
      fn: Property {},
      n: Property {},
      email: [Property]
    }
  }
]
```
