### ISSUE TITLE
camelcase dependency browser support

### ISSUE THREAD

**Issue by paweljedrzejczyk** [jhermsmeier/node-vcf#18]
Hi!

Author of `camelcase` library decided to support only modern browsers since 4.0 version. 
https://github.com/sindresorhus/camelcase/issues/19
Therefore node-vcf requires the use of transpiler to make it work in old browsers.

Do you consider downgrading `camelcase` to 3.0 that exports es5 code? :)

**Comment by jhermsmeier** [comment]
Oh, thanks for bringing this up, I hadn't noticed!

Just had a glance at the changes between 3.x and 4.x, and this can be safely downgraded in this case – only style changes apart from https://github.com/sindresorhus/camelcase/pull/18, which doesn't affect this module (I think / hope).

Would you mind sending a quick PR to downgrade it?

**Comment by paweljedrzejczyk** [comment]
Sure ;) ^
Thanks for quick feedback!

**Comment by jhermsmeier** [comment]
Merged & published as `vcf@2.0.1`

**Comment by jhermsmeier** [comment]
Out of curiosity – which Browsers do you need to support, where `camelcase@4` doesn't work?

**Comment by paweljedrzejczyk** [comment]
Thanks!

I have Typescript with Webpack Dll Plugin, so all external dependencies (such as vcf) are not touched by Babel at all. 
The issue was in test environment - Karma with PhantomJS:
```
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR SyntaxError: Use of reserved word 'let' in strict mode
```
