### ISSUE TITLE
capitalDashCase not behaving as expected

### ISSUE THREAD

**Issue by adaxi** [jhermsmeier/node-vcf#21]
```js
card.add('MEMBER', '1a7935722bfa2289da2934b87769cd14')
```

This generates:

```
-M-E-M-B-E-R:1a7935722bfa2289da2934b87769cd14
```

I expected:
```
MEMBER:1a7935722bfa2289da2934b87769cd14
```

I fiddled with the following line to remove the case translation, but have not got a definitive fix:
https://github.com/jhermsmeier/node-vcf/blob/37c7bf15681d0270001e84da8644a35a76ae5c5d/lib/property.js#L54

**Comment by jhermsmeier** [comment]
The "quick fix" to this would be to not capital case the input to `card.add()` (which is what I thought it's going to be used like, as the lib tries to take care of the casing), i.e.:
```js
card.add( 'member', '1a7935722bfa2289da2934b87769cd14' )
```

**Comment by adaxi** [comment]
I must be tired, my brain seems to have omitted the `.toUpperCase()` when reading the code. I can indeed solve my issue by setting `member` to lower case.

Personally feel that the library is trying to be too smart. I would prefer having a vCard values represented as I set them in the first place.
