### ISSUE TITLE
Expected VERSION

### ISSUE THREAD

**Issue by zacharytyhacz** [jhermsmeier/node-vcf#30]
I am testing the parsing of vcard files with a bunch of sample vcard examples I found online.
The birthday on them seems to come up before the version number, which I would assumed wouldn't break the parse. 

I'm just concerned if one of my users uploads a similar vcard with this similar format of NOT having the version number as the first data field, this parser cannot parse it and will fail. 

Is this a standardized failure by the example site I got these sample vcards from that is never to be expected with a vcard? I was thinking that this package would still parse through and search for a version number, but it appears not. 

Let me know what y'all think. For right now, I'm just going to move the `BDAY` below the `VERSION` for now.

Error: 
```
SyntaxError: Invalid vCard: Expected "VERSION:\d.\d" but found "BDAY;VALUE=DATE:1963-09-21"
```
This is the one I'm trying to parse:
```
BEGIN:VCARD
BDAY;VALUE=DATE:1963-09-21
VERSION:3.0
N:Stenerson;Derik
FN:Derik Stenerson
ORG:Microsoft Corporation
ADR;TYPE=WORK,POSTAL,PARCEL:;;One Microsoft Way;Redmond;WA;98052-6399;USA
TEL;TYPE=WORK,MSG:+1-425-936-5522
TEL;TYPE=WORK,FAX:+1-425-936-7329
EMAIL;TYPE=INTERNET:deriks@Microsoft.com
END:VCARD

BEGIN:VCARD
VERSION:3.0
N:Ganguly;Anik
FN:Anik Ganguly
ORG: Open Text Inc.
ADR;TYPE=WORK,POSTAL,PARCEL:;Suite 101;38777 West Six Mile Road;Livonia;MI;48152;USA
TEL;TYPE=WORK,MSG:+1-734-542-5955
EMAIL;TYPE=INTERNET:ganguly@acm.org
END:VCARD

BEGIN:VCARD
VERSION:3.0
N:Moskowitz;Robert
FN:Robert Moskowitz
EMAIL;TYPE=INTERNET:rgm-ietf@htt-consult.com
END:VCARD
```

**Comment by jhermsmeier** [comment]
Hi @zacharytyhacz, the reason for that error is that the [specification mandates](https://tools.ietf.org/html/rfc6350#section-6.7.9) that the version must be the second value in a vCard – except in version 2.1, where it may appear anywhere in the vCard.

This implementation currently also rejects this for version 2.1 though, which is something that'll need fixing:

https://github.com/jhermsmeier/node-vcf/blob/e0a984fb294fb2b76f0e6bba009357f15195b92d/lib/vcard.js#L271-L273
