### ISSUE TITLE
Version 2.0.6 fails to parse vcard files created by 2.0.4

### ISSUE THREAD

**Issue by rbeeger** [jhermsmeier/node-vcf#34]
2.0.6 fixed the bug introduced in 2.0.5 that prevented it from parsing its own output.
But 2.0.6 fails to parse its own output generated by version 2.0.4

2.0.4 on the other hand is able to parse output from versions 2.0.4, 2.0.5 and 2.0.6

**Comment by jhermsmeier** [comment]
Well, issue #33 has been around since v1.0.0 judging by git blame, and since LF delimited VCF is technically malformed, I'm not sure what you'd like to change?

**Comment by rbeeger** [comment]
It's totally fine that 2.0.6 fixes the output to be wellformed, but it should still be able to parse output generated by an earlier version even if it is now considered to be malformed. 

And it's a patch level update. Patch updates shouldn't break that kind of thing.

**Comment by jhermsmeier** [comment]
> And it's a patch level update. Patch updates shouldn't break that kind of thing.

Patches fix bugs. This was a bug, not an API change. Sorry it broke something, but that broken something is likely broken for most other things that parse VCF as well.
I agree that this is very unfortunate breakage, but given that the bug has been around for that long and nobody had complained about it, I figured patch level would be fine.

> but it should still be able to parse output generated by an earlier version even if it is now considered to be malformed.

The issue with that is that it would break multi-line fields (i.e. some quoted-printable encoded data, see https://github.com/jhermsmeier/node-vcf/pull/31 for an example) or other line-folded values. If you know that you don't have line-folded values in your vCards, you could treat them with `.replace( /\n/g, '\r\n' )` before parsing though.
