### ISSUE TITLE
npm sourcecode not matching GitHub sourcecode

### ISSUE THREAD

**Issue by muuvmuuv** [jhermsmeier/node-vcf#43]
Just noticed that because on our end it says:

```
'Invalid vCard: Expected "VERSION:\\d.\\d" but found "'+ version +'"'
```

and not:

https://github.com/jhermsmeier/node-vcf/blob/master/lib/vcard.js#L280-L286

But package.json Version match.

Can you update the npm lib please?

**Comment by jhermsmeier** [comment]
That is because I forgot to publish, thanks for the heads-up!
HEAD of master is now tagged, and published as `vcf@2.1.1`
