### ISSUE TITLE
Try unix line breaks \n if windows does not give results

### ISSUE THREAD

**Issue by muuvmuuv** [jhermsmeier/node-vcf#44]
Just noticed that if a vCard uses `\n` for line breaks vcf returns and undefined version match error. This can happen. A workaround would be a check after the first normalize split:

https://github.com/jhermsmeier/node-vcf/blob/master/lib/vcard.js#L263

```js
if (lines.length <= 1) {
        lines = lines[0].split(/\n/g);
      }
```

**Comment by jhermsmeier** [comment]
VCF specifies CRLF line endings; see https://github.com/jhermsmeier/node-vcf/issues/35#issuecomment-541233068 for a little more detail (tldr; it would break quoted printable encoding in values)
