### ISSUE TITLE
Unsupported version ARD

### ISSUE THREAD

**Issue by Zarinia** [jhermsmeier/node-vcf#47]
Hi,
When loading v4 vcard as a new vCard.parse failed with return code:
```
Error: Unsupported version \"ARD\"
```

**Comment by jhermsmeier** [comment]
Can you share the the beginning of the vcard it's not parsing?

**Comment by dkaufmannPa** [comment]
you can use:

`replace(/\r?\n/g, "\r\n");`

to do it

**Comment by jhermsmeier** [comment]
> which I guess it technically correct, since RFC 6350 requires a CRLF

Yes, single LF line endings are invalid, as VCF can have folded lines (which use a single LF), which is also why simply replacing LF with CRLF is generally unsafe (unless you *know* that your input does not have folded property lines). The respective cards would need to be re-exported and care taken to not mangle line endings.
