### ISSUE TITLE
Lines splitting supports only \r\n. 

### ISSUE THREAD

**Issue by nyxeet** [jhermsmeier/node-vcf#51]
The current implementation uses string.split(/\r\n/g) to split strings based on newline characters. This approach only handles the \r\n sequence, which is the newline convention used in Windows. It does not account for newline characters used in other operating systems, such as \n (used in Unix/Linux and modern macOS) and \r (used in older versions of macOS).

Proposed Change:

Replace the current implementation:

string.split(/\r\n/g) with string.split(/\r\n|\r|\n/)

**Comment by jhermsmeier** [comment]
Folded lines are unfolded according to https://datatracker.ietf.org/doc/html/rfc6350#section-3.2, where CRLF is mandated. This issue has come up at least three times before, search the closed issues for more detail.
